remote_theme: "mmistakes/minimal-mistakes@4.26.2" 
minimal_mistakes_skin: "dark" # Try "air", "aqua", "contrast", "dark", "default", "dirt", "mint", "sunrise"

title: Maggie Conboy
subtitle: "Transforming Enterprise Strategy Through AI Innovation"
name: Maggie Conboy
description: "Senior Product Manager driving $100M+ initiatives at GitHub"

author:
  name: "Maggie Conboy"
  avatar: "/assets/images/your-photo.jpg"
  bio: "Senior Product Manager at GitHub | AI Strategy Leader | Building the Future of Enterprise Software"
  location: "San Francisco, CA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/maggieconboy"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.email@github.com"

# Reading experience
read_time: true
words_per_minute: 200

# Navigation
header_pages:
  - index.md
  - portfolio.md
  - leadership.md

# Analytics (add your ID when ready)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "YOUR-ID"
