theme: jekyll-theme-primer
title: Maggie Conboy
description: Senior Product Manager | AI Leader | Restaurant Tech Pioneer
show_downloads: false

# This makes navigation appear
header_pages:
  - restaurant-portfolio.md

# This ensures proper URL structure
baseurl: "/Personal-Repo"
url: "https://maggieconboy.github.io"
