---
name: Semester Sizing
description: Semester Planning Engineering Sizing
title: "📏 Project Sizing"
labels: ["sizing"]
body:
  - type: markdown
    attributes:
      value: |
        # 📏 Project Sizing Template

        Use this template to gather details about the scope, complexity, and requirements of a project to estimate its size and timeline.

        - Answer the structured questions below to provide necessary context.
        - Once filled, this information will be used to generate a detailed sizing breakdown.

  - type: textarea
    id: initial_issue_description
    attributes:
      label: Initial Issue Description
      description: Copy and paste the problem statement and context provided by the Product Manager.
      placeholder: Include the initial issue description here or link to the original issue for reference.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 1. Scope and Complexity"
  
  - type: dropdown
    id: project_type
    attributes:
      label: Is this project an enhancement to an existing service or a completely new service?
      description: Select the type of project.
      options:
        - "Enhancement to an existing service"
        - "Completely new service"
    validations:
      required: true
  
  - type: textarea
    id: systems_or_components
    attributes:
      label: Will this project require changes to multiple systems or components?
      description: Specify the systems or components involved (e.g., frontend, backend, third-party integrations).
      placeholder: List the systems or components impacted.
    validations:
      required: true
  
  - type: textarea
    id: api_changes
    attributes:
      label: Does the implementation involve creating or modifying APIs?
      description: If yes, specify how many endpoints are affected.
      placeholder: List the number and type of APIs affected.
    validations:
      required: true
  
  - type: textarea
    id: database_changes
    attributes:
      label: Will the project require significant database changes?
      description: Specify the type of database changes (e.g., schema updates, migrations).
      placeholder: Describe the database changes required.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 2. Dependencies"
  
  - type: textarea
    id: dependencies
    attributes:
      label: Are there dependencies on other teams, external services, or third-party vendors for this project?
      description: List the dependencies and any potential risks they introduce.
      placeholder: Describe dependencies here.
    validations:
      required: true
  
  - type: textarea
    id: external_approvals
    attributes:
      label: Will there be external approvals required?
      description: Specify if approvals are required from security, compliance, or external partners.
      placeholder: Describe external approval requirements.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 3. Design and Alignment"
  
  - type: dropdown
    id: technical_design
    attributes:
      label: Does this project require a new technical design document or significant architectural changes?
      description: Indicate whether a new design or architecture is needed.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  
  - type: textarea
    id: alignment_with_teams
    attributes:
      label: Will alignment with other teams or stakeholders be necessary for this design?
      description: Describe the alignment required and any associated challenges.
      placeholder: Describe alignment needs.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 4. Testing and Quality Assurance"
  
  - type: textarea
    id: testing_type
    attributes:
      label: What type of testing will be required?
      description: Specify the types of testing (e.g., unit tests, integration tests, manual testing).
      placeholder: List the testing requirements.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 5. Security and Compliance"
  
  - type: dropdown
    id: security_review
    attributes:
      label: Will this project require a security or privacy review?
      description: Indicate whether a security or privacy review is necessary due to sensitive data handling.
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 6. Deployment and Release"
  
  - type: textarea
    id: feature_flags
    attributes:
      label: Will this project use feature flags for a phased rollout? If yes, how many phases are planned?
      description: Specify the number of phases or describe the rollout strategy.
      placeholder: Describe feature flag requirements.
    validations:
      required: true
  
  - type: textarea
    id: release_readiness_requirements
    attributes:
      label: Are there specific release readiness requirements?
      description: List any ticketing, on-call prep, or other requirements.
      placeholder: Describe release readiness needs.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### 7. Monitoring and Maintenance"
  
  - type: textarea
    id: monitoring_alerting_requirements
    attributes:
      label: Are there new monitoring or alerting requirements for this project?
      description: Specify what needs to be monitored or alerted post-release.
      placeholder: Describe monitoring needs.
    validations:
      required: true
  
  - type: textarea
    id: operational_risks
    attributes:
      label: Does this project introduce new operational risks or require post-release maintenance?
      description: Describe any risks or maintenance considerations.
      placeholder: Describe operational risks or maintenance needs.
    validations:
      required: true
